# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([5,8,9])
arr1

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[6, 11, 8],
               [2, 3, 23]])
arr2

array([[ 6, 11,  8],
       [ 2,  3, 23]])

In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
arr1= np.array([5,8,9])
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
arr2 = np.array([[6, 11, 9],
               [2, 3, 23]])
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(a2)

NameError: name 'a2' is not defined

In [5]:
# Create an array of shape (5, 5) with only ones
ones=np.ones([5,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
zeros=np.zeros((3,3,5))
zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[0, 6],
       [1, 7],
       [6, 0],
       [0, 4],
       [0, 0],
       [3, 4],
       [0, 9]])

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomArray = np.random.random((3, 5))
randomArray

array([[0.01333924, 0.94611957, 0.51641634, 0.86402828, 0.09380184],
       [0.78836812, 0.12638263, 0.42226182, 0.88187219, 0.94200476],
       [0.36102005, 0.08113256, 0.6825771 , 0.12338317, 0.30343565]])

In [9]:
# Create an array of normally distributed random numbers

Normal_Dis = np.random.normal(0.5,5,15)
Normal_Dis

array([ 0.82190606,  1.02551961, -3.50254957,  0.92905635, -3.36845693,
        3.8499673 ,  1.25012993, -3.2246283 ,  3.55104073, -2.11062825,
        3.313295  ,  2.91272518, -1.77085543, -1.78981927, -4.31685803])

In [10]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr = np.random.randint(10, size=(4,6))
random_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [11]:
# Copy the code from the cell above and run it again
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr = np.random.randint(10, size=(4,6))
random_arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [12]:
# Find the 0'th index of the latest array you created
random_arr[0]

array([6, 3, 7, 4, 6, 9])

In [13]:
# Get the first 2 rows of latest array you created
random_arr[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[:2,:2]

array([[6, 3],
       [2, 6]])

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
Array = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))
Array, ones

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [16]:
# Add the two arrays together
Array + ones

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

In [17]:
# Create another array of ones of shape (5, 3)
Ones = np.ones((5,3))
Ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
Array + Ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [19]:
# Do the same operation you just did but this time with a transpose on one array
Array.T + Ones

array([[ 9.,  4.,  7.],
       [ 1.,  9.,  5.],
       [10.,  3.,  9.],
       [ 3.,  5.,  7.],
       [ 7.,  3.,  2.]])

In [20]:
# Take the latest array to the power of 2 using the python way
Array ** 2

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]], dtype=int32)

In [21]:
# Do the same thing with numpy way
np.power(Array, 2)

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]], dtype=int32)

In [22]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(Array), np.max(Array), np.min(Array), np.std(Array), np.var(Array)

(4.6, 9, 0, 2.8000000000000003, 7.840000000000002)

In [23]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
r1 = np.random.randint(10, size = (3,3))
r2 = np.random.randint(10, size = (3,2))
r1 , r2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]), array([[6, 7],
        [2, 0],
        [3, 1]]))

In [24]:
# Perform a dot product on the two newest arrays you created
np.dot(r1, r2)

array([[37, 22],
       [97, 72],
       [35, 31]])

In [25]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
a1 = np.random.randint(10, size = (4,3))
a2 = np.random.randint(10, size = (4,3))
a1, a2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]), array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

In [26]:
# Perform a hadamard product on the two newest arrays you created
a1 * a2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

In [27]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(a1, a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [28]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(a1, a2.T)

array([[ 48,  81,  26,  95],
       [104, 111,  88, 157],
       [ 50,  63,  30,  75],
       [ 88, 115,  76, 161]])

In [29]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
a1 = np.random.randint(10, size = (3,5))
a2 = np.random.randint(10, size = (3,5))

In [30]:
# Compare the two arrays with '>', '<=' and '==' 
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [31]:
a2

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [32]:
a1 > a2

array([[False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [ True, False, False, False, False]])

In [33]:
a1 <= a2

array([[ True, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [34]:
a1 == a2

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [35]:
# Sort one of the arrays you just created in ascending order
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [36]:
np.sort(a1)

array([[0, 6, 7, 8, 8],
       [0, 0, 2, 7, 7],
       [0, 2, 2, 4, 7]])

In [37]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([0, 1, 2], dtype=int64)

In [38]:
# Find the index with the maximum value in one of the arrays you've created
arr1

array([5, 8, 9])

In [39]:
np.argmax(arr1)

2

In [40]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [41]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
arr1

array([5, 8, 9])

In [42]:
np.argmax(arr1,axis=0)

2

In [43]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
arr2

array([[ 6, 11,  9],
       [ 2,  3, 23]])

In [44]:
np.argmin(arr2,axis=1)

array([0, 0], dtype=int64)